--- #YAML:1.0
name:                Date-PeriodParser
version:             0.07
abstract:            Turns English descriptions into time periods
license:             ~
author:              
    - Joe McMahon <mcmahon@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Date::Calc:                    0
    Lingua::EN::Words2Nums:        0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
