# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-PeriodParser
version:      0.03
version_from: PeriodParser.pm
installdirs:  site
requires:
    Lingua::EN::Words2Nums:        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
